version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: taskmanager-mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME} 
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: TaskManagerDb 
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  api:
    build: 
      context: . 
      dockerfile: ./Build/TaskManagerApi.Dockerfile
    container_name: taskmanager-api
    ports:
      - "8000:80" # Map container port 80 to host port 8000
    depends_on:
      - mongodb
    environment: # Here we would insert sensitive variables from our CD
      - TM_MongoDbConnectionString=${TM_MongoDbConnectionString}
      - TM_JwtKey=${TM_JwtKey}
volumes:
  mongodb_data: