version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: taskmanager-mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME} 
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: TaskManagerDb 
    ports:
      - "27016:27017"
    volumes:
      - mongodb_data:/data/db

  api:
    build: 
      context: . 
      dockerfile: ./Build/TaskManagerApi.Dockerfile
    container_name: taskmanager-api
    ports:
      - "8001:8080"        
      - "8443:443"   
    depends_on:
      - mongodb
    environment: # Here we would insert sensitive variables from our CD
      - ASPNETCORE_URLS=https://+:443;http://+:8080
      - ASPNETCORE_Kestrel__Certificates__Default__Password=${CertPass}
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/etc/ssl/certs/aspnetapp.pfx
      - TM_MongoDbConnectionString=${TM_MongoDbConnectionString}
      - TM_JwtKey=${TM_JwtKey}

  ui:
    build: 
      context: .
      dockerfile: ./Build/TaskManagerUI.Dockerfile
    container_name: taskmanager-ui
    ports:      
      - "4220:443"  # HTTPS
      - "4200:80"    # Optional, if you still want HTTP support
    depends_on:
      - api # Ensure the API is running before the UI
    environment:
      - API_URL=https://taskmanager-api:8443 # Use the container name for HTTPS communication
volumes:
  mongodb_data: